### ISSUE TITLE
Error message for missing config file is not helpful

### ISSUE THREAD

**Issue by emfrost** [park-bench/netcheck#3]
When the daemon is started with no config file, it quits because of a missing option. Additionally, our logger only writes to stdout, which is not displayed when attempting to start via systemd.

**Comment by eviljoel** [comment]
Should be resolved when we merge in [issue 2](https://github.com/park-bench/netcheck/issues/2).

**Comment by eviljoel** [comment]
We now explicitly check for missing configuration files. The more global logging issues will be fixed in the next release and are being tracked in ticket https://github.com/park-bench/gpgmailer/issues/18 . Closing.
